# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Test

on:
  push:
    branches:
      - fix_test_not_working_in_workflow
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: "3.9" # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION_STRING: ${{secrets.DB_CONNECTION_STRING}}
      FUNCTIONS_WORKER_RUNTIME: "python"
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      NCLOUD_aCCESS_KEY: ${{secrets.NCLOUD_ACCESS_KEY}}
      NCLOUD_SECRET_KEY: ${{secrets.NCLOUD_SECRET_KEY}}
      NCLOUD_SMS_SERVICE_ID: ${{secrets.NCLOUD_SMS_SERVICE_ID}}
      NCLOUD_SMS_sERVICE_PHONE_NUMBER: ${{secrets.NCLOUD_SMS_SERVICE_PHONE_NUMBER}}
      YONSEI_AUTH_FUNCTION_ENDPOINT: ${{secrets.YONSEI_AUTH_FUNCTION_ENDPOINT}}
      YONSEI_AUTH_FUNCTION_CODE: ${{secrets.YONSEI_AUTH_FUNCTION_CODE}}
      PORTAL_ID: ${{secrets.PORTAL_ID}}
      PORTAL_PW: ${{secrets.PORTAL_PW}}
      REAL_NAME: ${{secrets.REAL_NAME}}
      USERNAME: ${{secrets.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
      NEW_PW: ${{secrets.NEW_PW}}
      HR_MANAGER_TEL: ${{secrets.HR_MANAGER_TEL}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test
        run: |
          pytest -n 1
